INSERT INTO `comm_templates`(
    `id`,
    `tag`,
    `name`,
    `subject`,
    `body`,
    `org_id`,
    `createdBy`,
    `updatedBy`,
    `updated_at`,
    `deletedBy`,
    `deleted_at`
)
VALUES(
    NULL,
    'schedule_auto_notify',
    'Auto Scheduling Notification',
    'Event scheduled',
    'Your have been placed on the schedule. (Auto assigned)',
    '0',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),(
    NULL,
    'schedule_manual_notify',
    'Scheduling event',
    'Event Scheduled',
    'Your Event has been scheduled, please follow the below mentioned details.',
    '0',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),(
    NULL,
    'schedule_confirmation',
    'Schedule confirmation',
    'Schedule Confirmation',
    'You have been placed on the schedule for the following dates. To respond or simply view this schedule, click the appropriate button below.',
    '0',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),(
    NULL,
    'schedule_reminder',
    'Schedule Remind',
    'Schedule Remind',
    'A Reminder that your event has been scheduled for below listed dates.',
    '0',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),(
    NULL,
    'schedule_check_out_notification_to_guest',
    'Schedule check out notification to guest',
    'Event Schedule Notification',
    'This is notify that event has been scheduled.thank_you_for_service',
    '0',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),(
    NULL,
    'thank_you_for_service',
    'Thanks for your service',
    'Thanks for Service',
    'Thanks for attending the below listed event.',
    '0',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
),
(
    NULL,
    'schedule_canceled',
    'Schedule canceled',
    'Schedule canceld',
    'sorry to inform you that. Your scheduled event has been canceled. For further information contact administrator.',
    '0',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
)